package edu.tum.ls1.mibo.editor.client.webcomponents;

public enum WCEventType {
	
	    DEFINITION_SECTION_CLICK_INFO,
	    DEFINITION_SECTION_CLICK_ADD,
	    DEFINITION_SECTION_DROP,
	    DEFINITION_SECTION_DRAG_ENTER,
	    DEFINITION_SECTION_DRAG_OVER,
	    DEFINITION_SECTION_DRAG_LEAVE,
	    DEFINITION_SECTION_DRAG_END,
	    DEFINITION_SECTION_CLICK_STATE,
	    TOOLBAR_AREA_CLICK_BACK,
	    TOOLBAR_AREA_CLICK_ATTRIBUTE,
	    WEBCOMPONENT_ITEM_CLICK_DELETE,
	    WEBCOMPONENT_ITEM_CLICK_INFO,
	    WEBCOMPONENT_ITEM_DRAG_STARTED,
	    WEBCOMPONENT_ITEM_DRAG_ENDED,
	    INSPECTOR_AREA_CLICK_CLEAR,
	    INSPECTOR_ITEM_CLICK_SAVE,
	    INSPECTOR_ITEM_CLICK_REMOVE,
	    CONTROL_ITEM_DROP,
	    CONTROL_ITEM_DRAG_ENTER,
	    CONTROL_ITEM_DRAG_OVER,
	    CONTROL_ITEM_DRAG_LEAVE,
	    CONTROL_ITEM_DRAG_END,
	    CONSOLE_AREA_CLICK_CLEAR,
	    LIST_SECTION_ITEM_NEXT,
	    LIST_SECTION_ITEM_DELETE,
	    LIST_SECTION_ITEM_EDIT,
	    LIST_SECTION_CLICK_ADD,
	    LIST_SECTION_CLICK_EXPAND,
	    LIST_SECTION_CLICK_UNEXPAND,
	    ACTION_AREA_CLICK_DEBUG,
	    ACTION_AREA_CLICK_COMPILE,
	    ACTION_AREA_CLICK_APPLY,
	    ACTION_AREA_CLICK_TEST
	    
}
